openapi: "3.0.1"
info:
  title: "Identity Service"
  version: v1
servers:
- url: https://localhost:8089/api
  description: Local instance

paths:
  /v1/ids:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArrayOfResourceIdentities"
      responses:
        '200':
          description: System IDs for the given public ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfRegistrations'
        '400':
          $ref: '#/components/responses/BadRequest'
  /v1/ids/{publicId}:
    get:
      summary: Look up system IDs for the given public ID
      operationId: lookup
      parameters:
      - in: path
        name: publicId
        schema:
          type: string
        required: true
      responses:
        '200':
          description: System IDs for the given public ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfResourceIdentities'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  responses:
    BadRequest:
      description: The request was not understood
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The ID was not found and is unknown to any system.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
          description: Milliseconds since the epoch
        message:
          type: string
        type:
          type: string
      required:
      - message
    ResourceIdentity:
      type: object
      properties:
        identifier:
          type: string
        resource:
          type: string
          pattern: "[-A-Za-z0-9_]"
        system:
          type: string
    ArrayOfResourceIdentities:
      type: array
      items:
        $ref: "#/components/schemas/ResourceIdentity"
    Registration:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        resourceIdentities:
          $ref: "#/components/schemas/ArrayOfResourceIdentities"
    ArrayOfRegistrations:
      type: array
      items:
        $ref: "#/components/schemas/Registration"
